package com.ahmetemresanli.backend.controller.impl;
import com.ahmetemresanli.backend.controller.ICandidateContentController; import com.ahmetemresanli.backend.dto.request.*; import com.ahmetemresanli.backend.dto.response.*; import com.ahmetemresanli.backend.service.ICandidateContentService;
import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.util.List;

@RestController @RequestMapping("/api/candidates/{candidateId}")
public class CandidateContentControllerImpl implements ICandidateContentController {
 private final ICandidateContentService service; public CandidateContentControllerImpl(ICandidateContentService service){this.service=service;}
 @Override @PostMapping("/projects") @PreAuthorize("@access.ownsCandidate(#candidateId)") public ResponseEntity<ProjectResponse> addProject(@PathVariable("candidateId") Long candidateId,@Valid @RequestBody ProjectRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(service.addProject(candidateId,r));}
 @Override @GetMapping("/projects") @PreAuthorize("@access.ownsCandidate(#candidateId) or hasAnyRole('COMPANY','ADMIN')") public ResponseEntity<List<ProjectResponse>> projects(@PathVariable("candidateId") Long candidateId){return ResponseEntity.ok(service.projects(candidateId));}
 @Override @DeleteMapping("/projects/{id}") @PreAuthorize("@access.ownsCandidate(#candidateId)") public ResponseEntity<Void> deleteProject(@PathVariable("candidateId") Long candidateId,@PathVariable Long id){service.deleteProject(candidateId,id);return ResponseEntity.noContent().build();}
 @Override @PostMapping("/certificates") @PreAuthorize("@access.ownsCandidate(#candidateId)") public ResponseEntity<CertificateResponse> addCertificate(@PathVariable("candidateId") Long candidateId,@Valid @RequestBody CertificateRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(service.addCertificate(candidateId,r));}
 @Override @GetMapping("/certificates") @PreAuthorize("@access.ownsCandidate(#candidateId) or hasAnyRole('COMPANY','ADMIN')") public ResponseEntity<List<CertificateResponse>> certificates(@PathVariable("candidateId") Long candidateId){return ResponseEntity.ok(service.certificates(candidateId));}
 @Override @DeleteMapping("/certificates/{id}") @PreAuthorize("@access.ownsCandidate(#candidateId)") public ResponseEntity<Void> deleteCertificate(@PathVariable("candidateId") Long candidateId,@PathVariable Long id){service.deleteCertificate(candidateId,id);return ResponseEntity.noContent().build();}
 @Override @PostMapping("/languages/catalog") @PreAuthorize("hasRole('ADMIN')") public ResponseEntity<LanguageResponse> createLanguage(@Valid @RequestBody LanguageRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(service.createLanguage(r.name()));}
 @Override @GetMapping("/languages/catalog") public ResponseEntity<List<LanguageResponse>> languages(){return ResponseEntity.ok(service.languages());}
 @Override @PostMapping("/languages") @PreAuthorize("@access.ownsCandidate(#candidateId)") public ResponseEntity<LanguageResponse> addLanguage(@PathVariable("candidateId") Long candidateId,@Valid @RequestBody CandidateLanguageRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(service.addLanguage(candidateId,r));}
 @Override @GetMapping("/languages") @PreAuthorize("@access.ownsCandidate(#candidateId) or hasAnyRole('COMPANY','ADMIN')") public ResponseEntity<List<LanguageResponse>> candidateLanguages(@PathVariable("candidateId") Long candidateId){return ResponseEntity.ok(service.candidateLanguages(candidateId));}
 @Override @PostMapping("/favorites/{jobId}") @PreAuthorize("@access.ownsCandidate(#candidateId)") public ResponseEntity<FavoriteResponse> favorite(@PathVariable("candidateId") Long candidateId,@PathVariable Long jobId){return ResponseEntity.status(HttpStatus.CREATED).body(service.favorite(candidateId,jobId));}
 @Override @GetMapping("/favorites") @PreAuthorize("@access.ownsCandidate(#candidateId)") public ResponseEntity<List<FavoriteResponse>> favorites(@PathVariable("candidateId") Long candidateId){return ResponseEntity.ok(service.favorites(candidateId));}
 @Override @DeleteMapping("/favorites/{jobId}") @PreAuthorize("@access.ownsCandidate(#candidateId)") public ResponseEntity<Void> unfavorite(@PathVariable("candidateId") Long candidateId,@PathVariable Long jobId){service.unfavorite(candidateId,jobId);return ResponseEntity.noContent().build();}
}
