package com.ahmetemresanli.backend.service.impl;
import com.ahmetemresanli.backend.dto.request.*; import com.ahmetemresanli.backend.dto.response.*;
import com.ahmetemresanli.backend.entity.*; import com.ahmetemresanli.backend.enums.JobStatus;
import com.ahmetemresanli.backend.exception.*; import com.ahmetemresanli.backend.repository.*; import com.ahmetemresanli.backend.service.ICandidateContentService;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDate; import java.util.List;

@Service
public class CandidateContentServiceImpl implements ICandidateContentService {
 private final CandidateProfileRepository candidates; private final ProjectRepository projects; private final CertificateRepository certificates;
 private final LanguageRepository languages; private final CandidateLanguageRepository candidateLanguages; private final FavoriteRepository favorites; private final JobPostingRepository jobs;
 public CandidateContentServiceImpl(CandidateProfileRepository candidates,ProjectRepository projects,CertificateRepository certificates,LanguageRepository languages,CandidateLanguageRepository candidateLanguages,FavoriteRepository favorites,JobPostingRepository jobs){this.candidates=candidates;this.projects=projects;this.certificates=certificates;this.languages=languages;this.candidateLanguages=candidateLanguages;this.favorites=favorites;this.jobs=jobs;}
 @Override public ProjectResponse addProject(Long id,ProjectRequest r){CandidateProfile c=candidate(id);if(r.startDate()!=null&&r.endDate()!=null&&r.endDate().isBefore(r.startDate()))throw new BusinessException("Project end date cannot be before start date");Project p=new Project();p.setCandidateProfile(c);p.setName(r.name().trim());p.setDescription(r.description());p.setProjectUrl(r.projectUrl());p.setRepositoryUrl(r.repositoryUrl());p.setStartDate(r.startDate());p.setEndDate(r.endDate());return map(projects.save(p));}
 @Override public List<ProjectResponse> projects(Long id){candidate(id);return projects.findByCandidateProfileIdOrderByCreatedAtDesc(id).stream().map(this::map).toList();}
 @Override public void deleteProject(Long c,Long id){Project p=projects.findById(id).filter(x->x.getCandidateProfile().getId().equals(c)).orElseThrow(()->new ResourceNotFoundException("Project not found"));projects.delete(p);}
 @Override public CertificateResponse addCertificate(Long id,CertificateRequest r){CandidateProfile c=candidate(id);if(r.issueDate()!=null&&r.issueDate().isAfter(LocalDate.now()))throw new BusinessException("Issue date cannot be in the future");if(r.issueDate()!=null&&r.expiryDate()!=null&&r.expiryDate().isBefore(r.issueDate()))throw new BusinessException("Expiry date cannot be before issue date");Certificate x=new Certificate();x.setCandidateProfile(c);x.setName(r.name().trim());x.setIssuer(r.issuer().trim());x.setIssueDate(r.issueDate());x.setExpiryDate(r.expiryDate());x.setCredentialId(r.credentialId());x.setCredentialUrl(r.credentialUrl());return map(certificates.save(x));}
 @Override public List<CertificateResponse> certificates(Long id){candidate(id);return certificates.findByCandidateProfileIdOrderByCreatedAtDesc(id).stream().map(this::map).toList();}
 @Override public void deleteCertificate(Long c,Long id){Certificate x=certificates.findById(id).filter(v->v.getCandidateProfile().getId().equals(c)).orElseThrow(()->new ResourceNotFoundException("Certificate not found"));certificates.delete(x);}
 @Override public LanguageResponse createLanguage(String name){if(languages.findByNameIgnoreCase(name.trim()).isPresent())throw new DuplicateResourceException("Language already exists");Language l=new Language();l.setName(name.trim());return new LanguageResponse(languages.save(l).getId(),l.getName(),null);}
 @Override public List<LanguageResponse> languages(){return languages.findByActiveTrueOrderByNameAsc().stream().map(l->new LanguageResponse(l.getId(),l.getName(),null)).toList();}
 @Override public LanguageResponse addLanguage(Long id,CandidateLanguageRequest r){CandidateProfile c=candidate(id);Language l=languages.findById(r.languageId()).filter(Language::isActive).orElseThrow(()->new ResourceNotFoundException("Language not found"));if(candidateLanguages.existsByCandidateProfileIdAndLanguageId(id,l.getId()))throw new DuplicateResourceException("Candidate already has this language");CandidateLanguage x=new CandidateLanguage();x.setCandidateProfile(c);x.setLanguage(l);x.setProficiency(r.proficiency());candidateLanguages.save(x);return new LanguageResponse(l.getId(),l.getName(),x.getProficiency());}
 @Override public List<LanguageResponse> candidateLanguages(Long id){candidate(id);return candidateLanguages.findByCandidateProfileId(id).stream().map(x->new LanguageResponse(x.getLanguage().getId(),x.getLanguage().getName(),x.getProficiency())).toList();}
 @Override @Transactional public FavoriteResponse favorite(Long id,Long jobId){CandidateProfile c=candidate(id);JobPosting j=jobs.findById(jobId).filter(x->x.getStatus()==JobStatus.PUBLISHED).orElseThrow(()->new ResourceNotFoundException("Published job posting not found"));if(favorites.existsByCandidateProfileIdAndJobPostingId(id,jobId))throw new DuplicateResourceException("Job is already a favorite");Favorite f=new Favorite();f.setCandidateProfile(c);f.setJobPosting(j);return map(favorites.save(f));}
 @Override public List<FavoriteResponse> favorites(Long id){candidate(id);return favorites.findByCandidateProfileIdOrderByCreatedAtDesc(id).stream().map(this::map).toList();}
 @Override public void unfavorite(Long id,Long jobId){Favorite f=favorites.findByCandidateProfileIdAndJobPostingId(id,jobId).orElseThrow(()->new ResourceNotFoundException("Favorite not found"));favorites.delete(f);}
 private CandidateProfile candidate(Long id){return candidates.findById(id).orElseThrow(()->new ResourceNotFoundException("Candidate profile not found"));}
 private ProjectResponse map(Project p){return new ProjectResponse(p.getId(),p.getCandidateProfile().getId(),p.getName(),p.getDescription(),p.getProjectUrl(),p.getRepositoryUrl(),p.getStartDate(),p.getEndDate(),p.getCreatedAt(),p.getUpdatedAt());}
 private CertificateResponse map(Certificate x){return new CertificateResponse(x.getId(),x.getCandidateProfile().getId(),x.getName(),x.getIssuer(),x.getIssueDate(),x.getExpiryDate(),x.getCredentialId(),x.getCredentialUrl(),x.getCreatedAt(),x.getUpdatedAt());}
 private FavoriteResponse map(Favorite f){return new FavoriteResponse(f.getId(),f.getCandidateProfile().getId(),f.getJobPosting().getId(),f.getJobPosting().getTitle(),f.getCreatedAt());}
}
